# Site settings
title: Yet Another Blog 
email: zihan.chen.jhu at gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Yet another blog. 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://zihanchen.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  zchen24

# Build settings
markdown: kramdown
highlighter: pygments